### ISSUE TITLE
Please rename src/whoosh_reloaded to src/whoosh for compatibility

### ISSUE THREAD

**Issue by cclauss** [Sygil-Dev/whoosh-reloaded#36]
```
  test_whoosh_backend.py", line 9, in <module>
      from whoosh.analysis import SpaceSeparatedTokenizer, SubstitutionFilter
  ModuleNotFoundError: No module named 'whoosh'
```

**Comment by ZeroCool940711** [comment]
The renaming was needed in order for us to be able to upload the package to PyPi since we dont have access to the old PyPi Whoosh project. It was also needed for visibility and to make it clear that the repo is not just a simple fork that didnt add anything but a continuation of Whoosh and that people should start using it from now on instead of the old repositories. 

In your example code you can install `whoosh-reloaded` with either `pip install whoosh-reloaded` or from the repo with `pip install git+https://github.com/Sygil-Dev/whoosh-reloaded.git` and then rename the import to `from whoosh_reloaded.analysis import SpaceSeparatedTokenizer, SubstitutionFilter` and it would work. I recommend a simple search and replace for all the imports, just replace `whoosh` with `whoosh_reloaded`.

**Comment by cclauss** [comment]
The Python Imaging Library (`PIL`) was abandoned around the time of Python 3 and everyone today uses the _friendly-fork_ named `Pillow` and this is how the `src` directory looks...
* https://github.com/python-pillow/Pillow/tree/main/src

I can come up with other instances if you need further proof...

I know the project name had to be changed for PyPI but renaming the file paths breaks all backward compatibility.

**Comment by ZeroCool940711** [comment]
Ok, I understand, sorry for the troubles. You are correct. It might be possible to keep the folder as `src/whoosh`. I will look into that tomorrow when I wake up since I'm probably about to go to sleep for today. The main issue I had was first because of my lack of knowledge on what we could and couldn't do to avoid issues with conflicts and to make it so we could install any old version of whoosh as well as our fork without having conflicts between them. I also have not a lot of experience working with projects as complex as whoosh and publishing them to PyPi, so, I'm learning as I go :)

**Comment by ZeroCool940711** [comment]
@cclauss just to confirm and be sure before I push the changes I have done. 
We want to rename the `src/whoosh_reloaded` folder back to `src/whoosh` so we can continue to use the imports like `from whoosh.analysis import SpaceSeparatedTokenizer, SubstitutionFilter ` instead of changing them to something new like `from whoosh_reloaded.analysis import SpaceSeparatedTokenizer, SubstitutionFilter` so you only need to change the location from where you are installing whoosh to our repo or use `pip install whoosh-reloaded` instead of `pip install whoosh` and everything should still be compatible with the old code, right?

If it is that way, then I can push the changes in a few minutes.

**Comment by cclauss** [comment]
That is correct.

**Comment by ZeroCool940711** [comment]
Done. PR #37 should have addressed this. Let me know if there are any issues.
