### ISSUE TITLE
Test coverage: Is there a codecov report?

### ISSUE THREAD

**Issue by cclauss** [Sygil-Dev/whoosh-reloaded#48]
We need more test coverage before we can continue to make changes...

https://github.com/whoosh-community/whoosh/pull/548#issuecomment-517777183 shows how little test coverage there is.

https://github.com/Sygil-Dev/whoosh-reloaded/pull/2#issuecomment-1925423142 shows no such report.

https://app.codecov.io/gh/Sygil-Dev/whoosh-reloaded needs to be set up and the token will need to be added to this repo as a GitHub Secret as discussed at https://docs.codecov.com/docs/adding-the-codecov-token#github-actions

https://github.com/Sygil-Dev/whoosh-reloaded/blob/f4165c2d09f3ce4654e2682c17da4755299500e7/.github/workflows/test.yml#L47

**Comment by ZeroCool940711** [comment]
I agree, we need more tests. The token for Codecov is already on the Github Secrets and it's used from there, the issue is that I think it is only looking at the `tests` folder and `setup.py` instead of looking at the whole project and all the files we have on the repo. It might be an issue with the Codecov configuration we are using for the repo or our Github Action. The report should be generated when Pytest runs here
https://github.com/Sygil-Dev/whoosh-reloaded/blob/f4165c2d09f3ce4654e2682c17da4755299500e7/.github/workflows/test.yml#L33-L37

**Comment by ZeroCool940711** [comment]
@cclauss I commented [on this PR](https://github.com/Sygil-Dev/whoosh-reloaded/pull/54#issuecomment-1931067355) I made yesterday that it seems like the Codecov and Sonarcloud.io bots are not configured properly, I tried fixing them but didnt make much progress. The Codecov report is also being generated differently locally vs the Github action. I could use some help fixing them.
